apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ollama-pvc  # Name of the PVC
  namespace: ollama  # Namespace - must be the same as where you deploy the Helm chart
spec:
  accessModes:
    - ReadWriteOnce  # Single node read-write
  resources:
    requests:
      storage: 30Gi  # Requested storage size
  storageClassName: default  # Name of the StorageClass
